const getInfo = require('./controllers/getInfo.js'),
      getTasks = require('./controllers/getTasks.js'),
      addTask = require('./controllers/addTask.js'),
      changeTaskStatus = require('./controllers/changeTaskStatus.js'),
      updateTask = require('./controllers/updateTask.js'),
      getTask = require('./controllers/getTask.js'),
      removeTask = require('./controllers/removeTask.js'),
      getUserInfo = require('./controllers/getUserInfo.js'),
      getUsersList = require('./controllers/getUsersList.js'),
      addComment = require('./controllers/addComment.js'),
      rateTask = require('./controllers/rateTask.js'),
      getStatistic = require('./controllers/getStatistic.js'),
      getTaskFromArchive = require('./controllers/getTaskFromArchive.js'),
      signIn = require('./controllers/signIn.js'),
      logIn = require('./controllers/logIn.js'),
      logOut = require('./controllers/logOut.js');

module.exports = {
    getInfo: getInfo,
    getTasks: getTasks,
    addTask: addTask,
    changeTaskStatus: changeTaskStatus,
    updateTask: updateTask,
    getTask: getTask,
    removeTask: removeTask,
    getUserInfo: getUserInfo,
    getUsersList: getUsersList,
    addComment: addComment,
    rateTask: rateTask,
    getStatistic: getStatistic,
    getTaskFromArchive: getTaskFromArchive,
    signIn: signIn,
    logIn: logIn,
    logOut: logOut,
}